### PR TITLE
merge latest master from upstream for upgrading

### PR DESCRIPTION
**Pull request by eatwithforks**
@zendesk/compute

### CODE REVIEW

**Review by uthark — APPROVED** [review]

**Comment by grosser** [comment]
now our master will be a giant mess 👎 
prefer to either: master == upstream or master == upstream+commits

**Comment by adammw** [comment]
rebasing master each time is much worse, you'll rewrite the one change you made multiple times. this way we see all the changes from upstream..

**Comment by adammw** [comment]
long lived branches always suck but have to contend with it for this unless they want to merge our stuff.

**Review by adammw — APPROVED** [review]

**Comment by grosser** [comment]
we want to have clean changes, so the changes should apply cleanly on upstream
-> keep the changes cleanly on their branches
-> make master mirror upstream (or never change it or have clean picked commits on it)
... otherwise we end up with a mess that can never be applied back to upstream

**Comment by adammw** [comment]
have a feature branch then for that change.. do you really think they're interested in merging it upstream at this point?

also fyi this repo is public so everyone can see us arguing :p

**Comment by grosser** [comment]
feature branch sounds good ... just leave master clean :)
if they want it or not, we should keep a clean branch ... for our sanity and so the PR is mergeable/reviewable if anyone else stumbles into this mess

**Pull request closed without merging**
